### PR TITLE
Correction json editor and adding a typescript editor

### PR DESCRIPTION
**Pull request by briangtn**
Correction json editor (Fail on load data.js) & adding a typescript editor with browserify (For browserify a file add "/// browserify" line in the typescript code

### CODE REVIEW

**Comment by elisee** [comment]
Hey! Thanks for the pull request.

Can you please submit the 2 unrelated changes (the new TypeScript editor and the JSON editor fix) as 2 separate pull requests, each with their own branch, so that we can review and merge them separately?

For future reference, check out the guidelines for sending a pull request [in the documentation][http://docs.superpowers-html5.com/en/development/how-to-contribute), especially regarding commit messages:

> - Use imperative in your commits message, for instance `Add flux capacitor` (not `Added a flux capacitor` neither `Adding flux capacitor`)
> - Try to stick to the existing coding style. You can use the tslint plugin in Visual Studio Code to help.
> - Make your pull request as small as possible. Don't bundle many unrelated changes together.

Thanks!

**Comment by briangtn** [comment]
Okey I do that !

**Comment by bilou84** [comment]
A few more notes from a quick review.
The .gitignore, README.md aren't necessary. I also believe locales/en/main.json isn't used anywhere ?

Last, this path is off.
https://github.com/superpowers/superpowers-web/pull/2/files#diff-3362b5a1c67510ffa4c72ad4afa8f817R3
It should be `/// <reference path="../../common/textEditorWidget/widget.d.ts" />`

**Comment by elisee** [comment]
One last nitpick about the commit message, can you capitalize it like this: `Fix JSON editor`?

**Comment by briangtn** [comment]
@bilou84 But my plugin follow the methods of JSON or Jade plugin ?! Oo

**Comment by bilou84** [comment]
This stuff has changed recently. You may have forked the repo before it happened. Have a look here.
https://github.com/superpowers/superpowers-web/blob/667080fdf3c79c663ddc7e46da6854598317f587/plugins/default/jade/index.d.ts

**Comment by briangtn** [comment]
Ahh in index.d.ts I've forgotten to update this file ! :p

**Comment by bilou84** [comment]
I can see the same probleme here.
https://github.com/coca44/superpowers-web/blob/9304ff38403124c8e1ad7916d7f75768ee7b8ed3/plugins/default/typescript/data/TypescriptAsset.ts#L1

**Pull request closed without merging**
